Fix Windows build failure by removing P2 mirror dependency in Spotless config
The Eclipse JDT formatter download via P2 mirrors (download.eclipse.org /
mirror.umd.edu) times out on Windows Docker containers in Jenkins CI,
causing the build to fail at Gradle configuration time with:
  java.io.IOException: Failed to load eclipse jdt formatter:
  java.net.SocketTimeoutException: Connect timed out

This removes the withP2Mirrors() call so Spotless resolves the Eclipse
formatter from Maven Central instead, matching what common-utils does.

Signed-off-by: Rithin Pullela <rithinp@amazon.com>
Signed-off-by: rithin-pullela-aws <rithinp@amazon.com>